package main

import (
	"log"
	"net/http"
	_ "rest-api-mux/docs" // docs is generated by Swag CLI, you have to import it.
	service "rest-api-mux/service"

	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger"
)

// @title task-mgmt-api
// @version 1.0
// @description This is task-mgmt api
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.email balajichandrasekar17@gmail.com
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host localhost:4000
// @schemes http
// @BasePath /

func main() {

	r := mux.NewRouter()
	r.HandleFunc("/get-task", service.Get_task).Methods("GET")
	r.HandleFunc("/create-task", service.Create_task).Methods("POST")
	r.HandleFunc("/update-task/{task_name}", service.Update_task).Methods("PUT")
	r.HandleFunc("/delete-task/{task_name}", service.Delete_task).Methods(http.MethodDelete)
	r.PathPrefix("/swagger").Handler(httpSwagger.WrapHandler)
	log.Fatal(http.ListenAndServe(":4000", r))

}
